[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "python"
# auto-format = true
language-server = { command = "pyright-langserver", args = ["--stdio"] }
roots = ["pyproject.toml"]
indent = { tab-width = 4, unit = "    " }
config = {}

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    "}

[[language]]
name = "astro"
auto-format = true
indent = { tab-width = 4, unit = "    "}


[[language]]
name = "ocaml"
auto-format = true
indent = { tab-width = 2, unit = "  "}
