[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 2, unit = " " }
